name: Deploy to Production

on:
  push:
    branches: ['main']

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gengar-bark:latest

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_SSHKEY }}
          command_timeout: 20m
          script: |
            docker stop gengar-bark
            docker rm gengar-bark
            docker rmi  ${{ secrets.DOCKERHUB_USERNAME }}/gengar-bark:latest
            docker pull  ${{ secrets.DOCKERHUB_USERNAME }}/gengar-bark:latest
            docker run -d --name gengar-bark -p 3001:3000 ${{ secrets.DOCKERHUB_USERNAME }}/gengar-bark
